### ISSUE TITLE
Header is not great.

### ISSUE THREAD

**Issue by krusynth** [opengovfoundation/free-law-founders-site#2]
@bryanconnor Can you take a few minutes to make some suggestions here?  This is the live site:

http://freelawfounders.org/

We'd really like to make this whole thing feel a bit more friendly and organic, since our audience is primarily lawmakers and secondarily citizens.  Any thoughts or advice would be appreciated!

cc:@cmbirk

**Comment by bryanconnor** [comment]
@krues8dr Sure thing! 

I think the header image is too generic and distracts from the page's main content. It doesn't really enhance my understanding of what this page is. My vote would be to remove the image entirely or at minimum replace it with some sort of less distracting illustration / iconography. 

More generally I think the container width for the site is too wide. Long blocks of text are a good deal easier to read when they're about half that width (around 65 characters per line).

I'm also not a huge fan of that beige color. I associate that color with lawyer's websites for some reason. 

Overall I'd say keep it clean, typographic, somewhat narrow with light visual elements or icons (perhaps even as a logo of sorts). 

Let me know if you have any questions about my suggestions. Happy to provide more!

**Comment by krusynth** [comment]
Thanks @bryanconnor I guess the issue here is that we _want_ it to look like a lawyer's website, since our audience is predominantly city officials.  We don't want too modern or icon-y for that very same reason, it needs to really look oldschool and trustworthy.

**Comment by bryanconnor** [comment]
@krues8dr  I think you're on the right track to trustworthy with the serif typeface you're using for the headings. I think another piece of it will be spending more time on the design of the site. At least for me, a site that has a well considered design is far more trustworthy than one without.

I'm not sure I agree with you on making this site look like the websites of its audience. I think the only real consistent style for most lawyers websites to draw from is poor design. It certainly has to be designed for its audience but I don't think emulating their sites will necessarily achieve that. 

http://internet.org/ is a nice example of something that's fairly typographic with a few colors that feels trustworthy and considered. 

The top of https://www.hioscar.com/ might also be applicable because of its bold typographic statement and goal of seeing trustworthy. (I understand the iconographic approach further down the page is less idea). 

Let me know if you need help brainstorming other header images to use as well.
